// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP2B2ppm-emCfXvXyFskAIJcVWvPRAFVo',
    appId: '1:914867790785:web:f7a1a7265fb69df1cd8540',
    messagingSenderId: '914867790785',
    projectId: 'fitness-tracker-414408',
    authDomain: 'fitness-tracker-414408.firebaseapp.com',
    storageBucket: 'fitness-tracker-414408.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJ27LHwiX0O2XXxbXkL2aal2sLeYCSek',
    appId: '1:914867790785:android:7c4480bc9371f987cd8540',
    messagingSenderId: '914867790785',
    projectId: 'fitness-tracker-414408',
    storageBucket: 'fitness-tracker-414408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYY3cmDi0p1eVowmkrYFvGA5jJVdz59g0',
    appId: '1:914867790785:ios:0cd6ce9875accabccd8540',
    messagingSenderId: '914867790785',
    projectId: 'fitness-tracker-414408',
    storageBucket: 'fitness-tracker-414408.appspot.com',
    iosBundleId: 'com.example.fitnessSync',
  );
}
